@echo off
set day=1
echo Name month (MM)
set /p month=
echo set year (YYYY)
set /p year=
set filename=%month%.01.%year% 
mkdir %filename%
set filename=%month%.02.%year% 
mkdir %filename%
set filename=%month%.03.%year% 
mkdir %filename%
set filename=%month%.04.%year% 
mkdir %filename%
set filename=%month%.05.%year% 
mkdir %filename%
set filename=%month%.06.%year% 
mkdir %filename%
set filename=%month%.07.%year% 
mkdir %filename%
set filename=%month%.08.%year% 
mkdir %filename%
set filename=%month%.09.%year% 
mkdir %filename%
set filename=%month%.10.%year% 
mkdir %filename%
set filename=%month%.11.%year% 
mkdir %filename%
set filename=%month%.12.%year% 
mkdir %filename%
set filename=%month%.13.%year% 
mkdir %filename%
set filename=%month%.14.%year% 
mkdir %filename%
set filename=%month%.15.%year% 
mkdir %filename%
set filename=%month%.16.%year% 
mkdir %filename%
set filename=%month%.17.%year% 
mkdir %filename%
set filename=%month%.18.%year% 
mkdir %filename%
set filename=%month%.19.%year% 
mkdir %filename%
set filename=%month%.20.%year% 
mkdir %filename%
set filename=%month%.21.%year% 
mkdir %filename%
set filename=%month%.22.%year% 
mkdir %filename%
set filename=%month%.23.%year% 
mkdir %filename%
set filename=%month%.24.%year% 
mkdir %filename%
set filename=%month%.25.%year% 
mkdir %filename%
set filename=%month%.26.%year% 
mkdir %filename%
set filename=%month%.27.%year% 
mkdir %filename%
set filename=%month%.27.%year% 
mkdir %filename%
set filename=%month%.28.%year% 
mkdir %filename%
set filename=%month%.29.%year% 
mkdir %filename%
set filename=%month%.30.%year% 
mkdir %filename%
set filename=%month%.31.%year% 
mkdir %filename%

